### PR TITLE
feat: Generify lizard based analyzers

### PR DESCRIPTION
**Pull request by FilipSzm**
* Make base analyzer for lizard based analyzers

* Use base analyzer in every lizard based language

* Generify analyzer tests

### CODE REVIEW

**Review by ConsoleRunner — APPROVED** [review]
Approved, but for some reason most of the mock files were marked as modified, event though diffs are identical (same goes for paths). This might lead to unnecessary confusion in commit history. @FilipSzm could you please perform a little cleanup before we merge?

**Comment by FilipSzm** [comment]
Hi, I created a "generic" directory in the tests folder to store tests for all lizard-based language analyzers. With that, I also moved mock files in there. It's a little difficult to see the path change in github, but there is one from tests/... to tests/generic/... If you think there is no reason to create this subdirectory in tests, I will gladly delete it :)

**Comment by ConsoleRunner** [comment]
> Hi @ConsoleRunner , I created a "generic" directory in the tests folder to store tests for all lizard-based language analyzers. With that, I also moved mock files in there. It's a little difficult to see the path change in github, but there is one from tests/... to tests/generic/... If you think there is no reason to create this subdirectory in tests, I will gladly delete it :)

Ah, I missed that, thx for quick response - no need for reverting it, but please clarify what would classify as a non-generic test in that context.

**Comment by FilipSzm** [comment]
I named all analyzers made using the lizard library generic. I think this name is adequate because I doubt there will be another big library used for analyzers, and I think it's a better naming convention than something related to the lizard name. So in short, generic = lizard based

**Comment by ConsoleRunner** [comment]
> I named all analyzers made using the lizard library generic. I think this name is adequate because I doubt there will be another big library used for analyzers, and I think it's a better naming convention than something related to the lizard name. So in short, generic = lizard based

Alright, thanks for clarification 👍

**Pull request merged**
